# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170913_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'teacher/%Y%m', verbose_name='\u5934\u50cf'),
        ),
    ]
