# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default=b'\xe5\x85\xa8\xe5\x9b\xbd\xe7\x9f\xa5\xe5\x90\x8d', max_length=10, verbose_name='\u673a\u6784\u6807\u7b7e'),
        ),
    ]
