# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default=b'\xe5\x90\x8e\xe7\xab\xaf\xe5\xbc\x80\xe5\x8f\x91', max_length=20, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
